# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

PATH=~/.composer/vendor/bin:~/src/boris/bin:~/.emacs.d/site-lisp/emms/src:~/src/drush:/usr/local/MacGPG2/bin:/usr/local/opt/php54/bin:/usr/local/opt/openssl/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/usr/X11/bin:~/bin:~/.cabal/bin:/usr/local/share/npm/bin:~/.emacs.d/site-lisp/osx-dictionary:/Applications/git-annex.app/Contents/MacOS

# My aliases
alias lr='ls -altr'
alias emacsclient=/usr/local/bin/emacsclient
alias emacs2='/Applications/Emacs.app/Contents/MacOS/Emacs &'
alias emacs3='/Applications/Emacs.app/Contents/MacOS/Emacs --debug-init &'
alias gcb="git add . && git commit -m '$(date +'%a, %d %b %Y')'"

# My env
export TERM=xterm-256color
export HISTSIZE=100000 SAVEHIST=100000 HISTFILE=~/.zhistory
export DSLM_BASE=~/data/code/dslm_base/

fpath=(~/drush_zsh/zsh $fpath)
autoload -U compinit
compinit -i

alias bower='noglob bower'

cdpath=(~/.emacs.d ~/data/releases)

export PYTHONPATH=/usr/local/lib/python2.7/site-packages:$PYTHONPATH

export prod1=wweb1.int.colorado.edu
export prod2=wweb2.int.colorado.edu
export prod3=wweb3.int.colorado.edu
export prod4=wweb4.int.colorado.edu
export test1=wwebtest1.int.colorado.edu
export test2=wwebtest2.int.colorado.edu
export dev1=wwebdev1.int.colorado.edu
export dev2=wwebdev2.int.colorado.edu
export stage=wstage1.colorado.edu

fpath=(~/.zsh $fpath)
